// FloraFetch catalog data, 4 categories, 40 plants (10 per category).
// `slug` drives the image filename (/uploads/<slug>.jpg) and `imageQuery` is
// used by scripts/fetch-images to pull a matching professional photo.

const categories = [
  { name: 'Indoor Plants', description: 'Lush houseplants that thrive indoors with low to medium light.' },
  { name: 'Outdoor Plants', description: 'Hardy, sun-loving plants and flowers for gardens, balconies, and terraces.' },
  { name: 'Air Purifying Plants', description: 'Greenery that filters indoor air and boosts humidity for a healthier home.' },
  { name: 'Medicinal Plants', description: 'Herbs and plants valued for their healing, culinary, and wellness uses.' },
];

const plants = [
  // ---------- Indoor Plants ----------
  { category: 'Indoor Plants', slug: 'peace-lily', imageQuery: 'peace lily spathiphyllum houseplant',
    name: 'Peace Lily', botanical_name: 'Spathiphyllum wallisii',
    description: 'Elegant air-purifying plant with glossy leaves and graceful white blooms.',
    price: 1200, size: 'medium', stock_qty: 25, sunlight_req: 'Low', watering_freq: 'Weekly', is_pet_friendly: 0, is_low_maint: 1 },
  { category: 'Indoor Plants', slug: 'zz-plant', imageQuery: 'zz plant zamioculcas zamiifolia',
    name: 'ZZ Plant', botanical_name: 'Zamioculcas zamiifolia',
    description: 'Nearly indestructible glossy plant ideal for low-light corners.',
    price: 1500, size: 'medium', stock_qty: 30, sunlight_req: 'Low', watering_freq: 'Fortnightly', is_pet_friendly: 0, is_low_maint: 1 },
  { category: 'Indoor Plants', slug: 'snake-plant', imageQuery: 'snake plant sansevieria potted',
    name: 'Snake Plant', botanical_name: 'Dracaena trifasciata',
    description: 'Striking upright sword-like leaves that tolerate neglect and low light.',
    price: 1100, size: 'medium', stock_qty: 40, sunlight_req: 'Low', watering_freq: 'Fortnightly', is_pet_friendly: 0, is_low_maint: 1 },
  { category: 'Indoor Plants', slug: 'monstera', imageQuery: 'monstera deliciosa plant',
    name: 'Monstera Deliciosa', botanical_name: 'Monstera deliciosa',
    description: 'Iconic split-leaf tropical with dramatic fenestrated foliage.',
    price: 2200, size: 'large', stock_qty: 18, sunlight_req: 'Medium', watering_freq: 'Weekly', is_pet_friendly: 0, is_low_maint: 0 },
  { category: 'Indoor Plants', slug: 'pothos', imageQuery: 'golden pothos epipremnum plant',
    name: 'Golden Pothos', botanical_name: 'Epipremnum aureum',
    description: 'Fast-growing trailing vine with heart-shaped variegated leaves.',
    price: 700, size: 'small', stock_qty: 50, sunlight_req: 'Low', watering_freq: 'Weekly', is_pet_friendly: 0, is_low_maint: 1 },
  { category: 'Indoor Plants', slug: 'fiddle-leaf-fig', imageQuery: 'fiddle leaf fig ficus lyrata',
    name: 'Fiddle Leaf Fig', botanical_name: 'Ficus lyrata',
    description: 'Statement plant with large violin-shaped leaves for bright rooms.',
    price: 2800, size: 'large', stock_qty: 12, sunlight_req: 'High', watering_freq: 'Weekly', is_pet_friendly: 0, is_low_maint: 0 },
  { category: 'Indoor Plants', slug: 'chinese-evergreen', imageQuery: 'aglaonema chinese evergreen plant',
    name: 'Chinese Evergreen', botanical_name: 'Aglaonema commutatum',
    description: 'Colourful patterned foliage that thrives in low, indirect light.',
    price: 1300, size: 'medium', stock_qty: 22, sunlight_req: 'Low', watering_freq: 'Weekly', is_pet_friendly: 0, is_low_maint: 1 },
  { category: 'Indoor Plants', slug: 'philodendron', imageQuery: 'heartleaf philodendron plant',
    name: 'Heartleaf Philodendron', botanical_name: 'Philodendron hederaceum',
    description: 'Easygoing trailing vine with lush heart-shaped green leaves.',
    price: 900, size: 'small', stock_qty: 35, sunlight_req: 'Medium', watering_freq: 'Weekly', is_pet_friendly: 0, is_low_maint: 1 },
  { category: 'Indoor Plants', slug: 'calathea', imageQuery: 'calathea orbifolia plant',
    name: 'Calathea Orbifolia', botanical_name: 'Calathea orbifolia',
    description: 'Prayer plant with broad silver-striped leaves that fold at night.',
    price: 1600, size: 'medium', stock_qty: 16, sunlight_req: 'Medium', watering_freq: 'Weekly', is_pet_friendly: 1, is_low_maint: 0 },
  { category: 'Indoor Plants', slug: 'rubber-plant', imageQuery: 'rubber plant ficus elastica',
    name: 'Rubber Plant', botanical_name: 'Ficus elastica',
    description: 'Bold burgundy-green glossy leaves on an easy upright grower.',
    price: 1700, size: 'large', stock_qty: 20, sunlight_req: 'Medium', watering_freq: 'Weekly', is_pet_friendly: 0, is_low_maint: 1 },

  // ---------- Outdoor Plants ----------
  { category: 'Outdoor Plants', slug: 'bougainvillea', imageQuery: 'bougainvillea flowers magenta',
    name: 'Bougainvillea', botanical_name: 'Bougainvillea glabra',
    description: 'Vibrant climbing shrub with papery magenta bracts that loves full sun.',
    price: 900, size: 'large', stock_qty: 18, sunlight_req: 'High', watering_freq: 'Weekly', is_pet_friendly: 1, is_low_maint: 1 },
  { category: 'Outdoor Plants', slug: 'hibiscus', imageQuery: 'hibiscus red flower',
    name: 'Hibiscus', botanical_name: 'Hibiscus rosa-sinensis',
    description: 'Showy tropical shrub with large trumpet-shaped scarlet flowers.',
    price: 750, size: 'medium', stock_qty: 24, sunlight_req: 'High', watering_freq: 'Daily', is_pet_friendly: 1, is_low_maint: 0 },
  { category: 'Outdoor Plants', slug: 'marigold', imageQuery: 'marigold flowers orange',
    name: 'Marigold', botanical_name: 'Tagetes erecta',
    description: 'Cheerful golden-orange blooms that brighten beds and repel pests.',
    price: 350, size: 'small', stock_qty: 60, sunlight_req: 'High', watering_freq: 'Daily', is_pet_friendly: 1, is_low_maint: 1 },
  { category: 'Outdoor Plants', slug: 'damask-rose', imageQuery: 'damask rose pink rosa',
    name: 'Damask Rose', botanical_name: 'Rosa damascena',
    description: 'Fragrant pink rose prized for its scent and ornamental blooms.',
    price: 1100, size: 'medium', stock_qty: 20, sunlight_req: 'High', watering_freq: 'Daily', is_pet_friendly: 1, is_low_maint: 0 },
  { category: 'Outdoor Plants', slug: 'jasmine', imageQuery: 'arabian jasmine flower jasminum',
    name: 'Arabian Jasmine', botanical_name: 'Jasminum sambac',
    description: 'Intensely fragrant white blooms perfect for trellises and pots.',
    price: 850, size: 'medium', stock_qty: 28, sunlight_req: 'High', watering_freq: 'Weekly', is_pet_friendly: 1, is_low_maint: 1 },
  { category: 'Outdoor Plants', slug: 'sunflower', imageQuery: 'sunflower helianthus bloom',
    name: 'Sunflower', botanical_name: 'Helianthus annuus',
    description: 'Towering golden blooms that follow the sun and delight pollinators.',
    price: 400, size: 'large', stock_qty: 45, sunlight_req: 'High', watering_freq: 'Daily', is_pet_friendly: 1, is_low_maint: 1 },
  { category: 'Outdoor Plants', slug: 'lavender', imageQuery: 'lavender flowers field lavandula',
    name: 'Lavender', botanical_name: 'Lavandula angustifolia',
    description: 'Aromatic purple spikes loved by bees and used for calming oils.',
    price: 1250, size: 'medium', stock_qty: 26, sunlight_req: 'High', watering_freq: 'Weekly', is_pet_friendly: 1, is_low_maint: 1 },
  { category: 'Outdoor Plants', slug: 'petunia', imageQuery: 'petunia flowers colorful',
    name: 'Petunia', botanical_name: 'Petunia × hybrida',
    description: 'Prolific trumpet-shaped blooms in a rainbow of colours all season.',
    price: 450, size: 'small', stock_qty: 50, sunlight_req: 'High', watering_freq: 'Daily', is_pet_friendly: 1, is_low_maint: 1 },
  { category: 'Outdoor Plants', slug: 'geranium', imageQuery: 'geranium pelargonium flowers',
    name: 'Geranium', botanical_name: 'Pelargonium hortorum',
    description: 'Classic clustered blooms with fragrant foliage for pots and borders.',
    price: 600, size: 'small', stock_qty: 38, sunlight_req: 'High', watering_freq: 'Weekly', is_pet_friendly: 0, is_low_maint: 1 },
  { category: 'Outdoor Plants', slug: 'canna-lily', imageQuery: 'canna lily flower red',
    name: 'Canna Lily', botanical_name: 'Canna indica',
    description: 'Tropical statement plant with bold paddle leaves and fiery blooms.',
    price: 950, size: 'large', stock_qty: 22, sunlight_req: 'High', watering_freq: 'Daily', is_pet_friendly: 1, is_low_maint: 1 },

  // ---------- Air Purifying Plants ----------
  { category: 'Air Purifying Plants', slug: 'areca-palm', imageQuery: 'areca palm plant indoor',
    name: 'Areca Palm', botanical_name: 'Dypsis lutescens',
    description: 'Feathery arching fronds that humidify and filter indoor air.',
    price: 2400, size: 'large', stock_qty: 15, sunlight_req: 'Medium', watering_freq: 'Weekly', is_pet_friendly: 1, is_low_maint: 1 },
  { category: 'Air Purifying Plants', slug: 'spider-plant', imageQuery: 'spider plant chlorophytum',
    name: 'Spider Plant', botanical_name: 'Chlorophytum comosum',
    description: 'Arching striped leaves and baby plantlets; a proven air cleaner.',
    price: 650, size: 'small', stock_qty: 48, sunlight_req: 'Medium', watering_freq: 'Weekly', is_pet_friendly: 1, is_low_maint: 1 },
  { category: 'Air Purifying Plants', slug: 'boston-fern', imageQuery: 'boston fern nephrolepis',
    name: 'Boston Fern', botanical_name: 'Nephrolepis exaltata',
    description: 'Lush feathery fronds that thrive in humidity and purify the air.',
    price: 1000, size: 'medium', stock_qty: 24, sunlight_req: 'Medium', watering_freq: 'Daily', is_pet_friendly: 1, is_low_maint: 0 },
  { category: 'Air Purifying Plants', slug: 'english-ivy', imageQuery: 'english ivy hedera helix plant',
    name: 'English Ivy', botanical_name: 'Hedera helix',
    description: 'Trailing evergreen vine renowned for reducing airborne mould.',
    price: 800, size: 'small', stock_qty: 30, sunlight_req: 'Medium', watering_freq: 'Weekly', is_pet_friendly: 0, is_low_maint: 1 },
  { category: 'Air Purifying Plants', slug: 'dracaena', imageQuery: 'dracaena marginata plant',
    name: 'Dracaena Marginata', botanical_name: 'Dracaena marginata',
    description: 'Slender spiky red-edged leaves on an architectural air-purifier.',
    price: 1500, size: 'large', stock_qty: 20, sunlight_req: 'Medium', watering_freq: 'Weekly', is_pet_friendly: 0, is_low_maint: 1 },
  { category: 'Air Purifying Plants', slug: 'bamboo-palm', imageQuery: 'bamboo palm chamaedorea plant',
    name: 'Bamboo Palm', botanical_name: 'Chamaedorea seifrizii',
    description: 'Graceful clumping palm that filters toxins and adds humidity.',
    price: 2000, size: 'large', stock_qty: 16, sunlight_req: 'Medium', watering_freq: 'Weekly', is_pet_friendly: 1, is_low_maint: 1 },
  { category: 'Air Purifying Plants', slug: 'weeping-fig', imageQuery: 'ficus benjamina weeping fig',
    name: 'Weeping Fig', botanical_name: 'Ficus benjamina',
    description: 'Elegant weeping canopy of glossy leaves that scrubs the air.',
    price: 1800, size: 'large', stock_qty: 18, sunlight_req: 'Medium', watering_freq: 'Weekly', is_pet_friendly: 0, is_low_maint: 0 },
  { category: 'Air Purifying Plants', slug: 'chrysanthemum', imageQuery: 'chrysanthemum flowers potted',
    name: 'Chrysanthemum', botanical_name: 'Chrysanthemum morifolium',
    description: 'Cheerful blooms that top NASA’s list for removing indoor toxins.',
    price: 700, size: 'small', stock_qty: 34, sunlight_req: 'High', watering_freq: 'Weekly', is_pet_friendly: 0, is_low_maint: 0 },
  { category: 'Air Purifying Plants', slug: 'gerbera-daisy', imageQuery: 'gerbera daisy flower',
    name: 'Gerbera Daisy', botanical_name: 'Gerbera jamesonii',
    description: 'Bright cheerful daisies that release oxygen and filter benzene.',
    price: 550, size: 'small', stock_qty: 40, sunlight_req: 'High', watering_freq: 'Daily', is_pet_friendly: 1, is_low_maint: 0 },
  { category: 'Air Purifying Plants', slug: 'dieffenbachia', imageQuery: 'dieffenbachia dumb cane plant',
    name: 'Dumb Cane', botanical_name: 'Dieffenbachia seguine',
    description: 'Large variegated leaves that brighten rooms and clean the air.',
    price: 1200, size: 'medium', stock_qty: 22, sunlight_req: 'Medium', watering_freq: 'Weekly', is_pet_friendly: 0, is_low_maint: 1 },

  // ---------- Medicinal Plants ----------
  { category: 'Medicinal Plants', slug: 'aloe-vera', imageQuery: 'aloe vera plant',
    name: 'Aloe Vera', botanical_name: 'Aloe barbadensis miller',
    description: 'Soothing succulent whose gel heals burns and calms skin.',
    price: 500, size: 'small', stock_qty: 60, sunlight_req: 'Medium', watering_freq: 'Fortnightly', is_pet_friendly: 0, is_low_maint: 1 },
  { category: 'Medicinal Plants', slug: 'tulsi', imageQuery: 'holy basil tulsi plant',
    name: 'Holy Basil (Tulsi)', botanical_name: 'Ocimum tenuiflorum',
    description: 'Sacred aromatic herb used in teas to relieve stress and colds.',
    price: 400, size: 'small', stock_qty: 55, sunlight_req: 'High', watering_freq: 'Daily', is_pet_friendly: 1, is_low_maint: 1 },
  { category: 'Medicinal Plants', slug: 'mint', imageQuery: 'mint plant leaves mentha',
    name: 'Mint', botanical_name: 'Mentha spicata',
    description: 'Refreshing culinary herb that aids digestion and flavours drinks.',
    price: 300, size: 'small', stock_qty: 70, sunlight_req: 'Medium', watering_freq: 'Daily', is_pet_friendly: 1, is_low_maint: 1 },
  { category: 'Medicinal Plants', slug: 'neem', imageQuery: 'neem tree leaves azadirachta',
    name: 'Neem', botanical_name: 'Azadirachta indica',
    description: 'Time-honoured medicinal tree with antibacterial leaves and oil.',
    price: 950, size: 'large', stock_qty: 20, sunlight_req: 'High', watering_freq: 'Weekly', is_pet_friendly: 1, is_low_maint: 1 },
  { category: 'Medicinal Plants', slug: 'ashwagandha', imageQuery: 'ashwagandha withania plant',
    name: 'Ashwagandha', botanical_name: 'Withania somnifera',
    description: 'Adaptogenic herb whose roots are used to reduce stress and fatigue.',
    price: 1100, size: 'medium', stock_qty: 24, sunlight_req: 'High', watering_freq: 'Weekly', is_pet_friendly: 1, is_low_maint: 1 },
  { category: 'Medicinal Plants', slug: 'lemongrass', imageQuery: 'lemongrass plant cymbopogon',
    name: 'Lemongrass', botanical_name: 'Cymbopogon citratus',
    description: 'Citrus-scented grass used in teas, cooking, and mosquito repellents.',
    price: 450, size: 'medium', stock_qty: 42, sunlight_req: 'High', watering_freq: 'Daily', is_pet_friendly: 1, is_low_maint: 1 },
  { category: 'Medicinal Plants', slug: 'ginger', imageQuery: 'ginger plant zingiber',
    name: 'Ginger', botanical_name: 'Zingiber officinale',
    description: 'Warming rhizome herb valued for digestion and cold relief.',
    price: 550, size: 'small', stock_qty: 38, sunlight_req: 'Medium', watering_freq: 'Weekly', is_pet_friendly: 1, is_low_maint: 1 },
  { category: 'Medicinal Plants', slug: 'turmeric', imageQuery: 'turmeric plant curcuma',
    name: 'Turmeric', botanical_name: 'Curcuma longa',
    description: 'Golden anti-inflammatory rhizome with lush tropical foliage.',
    price: 600, size: 'medium', stock_qty: 36, sunlight_req: 'Medium', watering_freq: 'Weekly', is_pet_friendly: 1, is_low_maint: 1 },
  { category: 'Medicinal Plants', slug: 'chamomile', imageQuery: 'chamomile flowers matricaria',
    name: 'Chamomile', botanical_name: 'Matricaria chamomilla',
    description: 'Daisy-like blooms brewed into a soothing, sleep-promoting tea.',
    price: 500, size: 'small', stock_qty: 44, sunlight_req: 'High', watering_freq: 'Daily', is_pet_friendly: 1, is_low_maint: 1 },
  { category: 'Medicinal Plants', slug: 'curry-leaf', imageQuery: 'curry leaf plant murraya',
    name: 'Curry Leaf', botanical_name: 'Murraya koenigii',
    description: 'Aromatic culinary leaves rich in antioxidants for South Asian dishes.',
    price: 700, size: 'medium', stock_qty: 30, sunlight_req: 'High', watering_freq: 'Weekly', is_pet_friendly: 1, is_low_maint: 1 },
];

module.exports = { categories, plants };
